export const companyInfoStyles = {
  companyInfo: {
    backgroundColor: '#2c2c2c',
    borderRadius: '8px',
    padding: '20px',
    marginTop: '20px',
    boxShadow: '0 4px 6px rgba(0,0,0,0.1)',
  },
  infoGrid: {
    display: 'flex',
    flexDirection: 'row' as const,
    justifyContent: 'space-between',
    gap: '15px',
  },
  infoItem: {
    display: 'flex',
    flexDirection: 'column' as const,
    alignItems: 'center',
    gap: '5px',
    padding: '10px',
    backgroundColor: '#363636',
    borderRadius: '6px',
    flex: 1,
  },
  infoLabel: {
    fontSize: '0.8rem',
    color: '#a0a0a0',
    fontWeight: '500',
    textTransform: 'uppercase' as const,
    letterSpacing: '0.5px',
  },
  infoValue: {
    fontSize: '0.9rem',
    color: '#fff',
    textAlign: 'center' as const,
    lineHeight: '1.4',
  },
  reviewsSection: {
    marginTop: '20px',
    paddingTop: '20px',
    borderTop: '1px solid #404040',
    maxWidth: '800px',
  },
  reviewsHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '15px',
    cursor: 'pointer',
  },
  reviewsTitle: {
    color: '#fff',
    margin: '0',
    fontSize: '1.2rem',
  },
  toggleButton: {
    background: 'none',
    border: 'none',
    color: '#fff',
    fontSize: '1.2rem',
    cursor: 'pointer',
    padding: '5px',
    transition: 'transform 0.3s ease',
  },
  toggleButtonOpen: {
    transform: 'rotate(180deg)',
  },
  reviewsGrid: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '15px',
    maxHeight: '0',
    overflow: 'hidden',
    transition: 'max-height 0.3s ease-out',
  },
  reviewsGridOpen: {
    maxHeight: '1000px',
    transition: 'max-height 0.5s ease-in',
  },
  reviewItem: {
    backgroundColor: '#363636',
    borderRadius: '8px',
    padding: '15px',
  },
  reviewHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '10px',
  },
  reviewerName: {
    fontSize: '1rem',
    color: '#fff',
    fontWeight: '500',
  },
  reviewDate: {
    fontSize: '0.8rem',
    color: '#a0a0a0',
  },
  reviewRating: {
    display: 'flex',
    gap: '5px',
    marginBottom: '10px',
  },
  star: {
    color: '#ffd700',
    fontSize: '1.1rem',
  },
  reviewText: {
    fontSize: '0.95rem',
    color: '#e0e0e0',
    lineHeight: '1.5',
  },
  writeReviewButton: {
    backgroundColor: '#6B46C1',
    color: '#fff',
    border: '1px solid #805AD5',
    borderRadius: '4px',
    padding: '8px 16px',
    fontSize: '0.9rem',
    cursor: 'pointer',
    marginTop: '15px',
    width: '100%',
    transition: 'all 0.2s ease',
    '&:hover': {
      backgroundColor: '#805AD5',
    },
  },
  tooltipContainer: {
    position: 'relative' as const,
    width: '100%',
  },
  tooltip: {
    position: 'absolute' as const,
    bottom: '100%',
    left: '50%',
    transform: 'translateX(-50%)',
    backgroundColor: '#2c2c2c',
    color: '#fff',
    padding: '6px 10px',
    borderRadius: '4px',
    fontSize: '0.8rem',
    whiteSpace: 'nowrap' as const,
    marginBottom: '8px',
    boxShadow: '0 2px 4px rgba(0,0,0,0.2)',
    zIndex: '1000',
  },
};