name: Build and Deploy Node.js App to Azure Web App - MyOrgWallet-Service-Marketplace-Server

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'pnpm'  # Enable pnpm caching for faster builds

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          standalone: true

      - name: Add pnpm to PATH
        run: echo "$(npm bin -g)" >> $GITHUB_PATH

      - name: Install dependencies and build
        run: |
          pnpm install --no-frozen-lockfile
          pnpm --filter @mcp/shared build || echo "No build script for @mcp/shared"
          pnpm --filter ./server build || echo "No build script for server"
          pnpm --filter ./server test || echo "No test script"
        env:
          NODE_ENV: production  # Ensure production dependencies are installed

      - name: Verify build output
        run: |
          ls -l server/dist
          ls -l server/node_modules/@mcp/shared/dist || echo "Warning: @mcp/shared/dist not found"

      - name: Zip server folder and dependencies for deployment
        run: |
          zip -r release.zip server node_modules/@mcp -x "node_modules/.cache/*"
        env:
          NODE_ENV: production

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Extract artifact
        run: unzip release.zip -d .

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_8FC5F982D46F42FCBAEBB3986C5FF4A7 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_4373A42FD1C94DE39560B37E37E65BCB }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_C3277C12CE144809A14889F2824C47BF }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'MyOrgWallet-Service-Marketplace-Server'
          slot-name: 'Production'
          package: .